@file:Suppress("PackageDirectoryMismatch")

object Versions {

    const val gradleVersion = "7.3.0"
    const val kotlinVersion = "1.6.10"
    const val coreKtxVersion = "1.7.0"
    const val activityKtxVersion = "1.1.0"
    const val multidexVersion = "2.0.1"
    const val materialVersion = "1.5.0"
    const val material3Version = "1.0.0-alpha02"
    const val daggerHiltVersion = "2.42"
    const val gsonVersion = "2.8.6"
    const val retrofitVersion = "2.9.0"
    const val okHttpVersion = "4.9.3"
    const val coroutinesVersion = "1.6.0"
    const val ktlintVersion = "0.40.0"
    const val composeVersion = "1.1.1"
    const val composeActivityVersion = "1.4.0"
    const val composeViewModelVersion = "2.4.1"
    const val kotlinCompilerExtensionVersion = "1.1.1"
    const val composeConstraintLayoutVersion = "1.0.0"
    const val hiltNavigationCompose = "1.0.0"
    const val composeNavigationVersion = "2.4.1"
    const val composeSwipeRefreshVersion = "0.23.1"
    const val composeCoilVersion = "0.12.0"
    const val composePagingVersion = "1.0.0-alpha14"
    const val roomVersion = "2.4.2"
    const val lifecycleVersion = "2.3.1"
    const val lifecycleStateVersion = "2.5.1"
    const val timberVersion = "4.7.1"

    const val junit4Version = "4.13.2"
    const val junitExtensionsVersion = "1.1.3"
    const val espressoCoreVersion = "3.4.0"
}
